2023-10-30 13:47:15,902 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 13:47:15,904 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 13:47:15,904 INFO     [app.py:37] Logged in user: S3ARKLR, role: superadmin
2023-10-30 13:47:22,187 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 13:47:22,187 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 13:47:30,031 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 13:47:30,049 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 13:47:32,955 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 13:47:32,955 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 14:11:09,964 DEBUG    [db_connector.py:24] Database connection initialise
2023-10-30 14:13:16,829 DEBUG    [db_connector.py:24] Database connection initialise
2023-10-30 14:13:55,682 DEBUG    [db_connector.py:25] Database connection initialise
2023-10-30 14:13:55,682 ERROR    [db_connector.py:31] Some error occurred
2023-10-30 15:49:07,944 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:49:07,946 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 15:49:07,946 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:49:07,965 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 15:49:07,965 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:49:07,976 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 15:49:07,979 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:49:07,988 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 15:49:07,988 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:49:07,999 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 15:49:07,999 INFO     [users.py:86] User shreyansh Saved to Db
2023-10-30 15:49:07,999 INFO     [user_controller.py:65] User Saved to DB
2023-10-30 15:49:48,745 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:49:48,747 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 15:49:48,747 DEBUG    [user_controller.py:34] Pending User Attempted Login
2023-10-30 15:50:08,081 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:50:08,083 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 15:50:08,083 INFO     [app.py:43] Logged in user: S3ARKLR, role: superadmin
2023-10-30 15:50:36,622 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 15:50:36,629 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 17:32:40,121 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 17:32:40,123 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 17:32:40,123 INFO     [app.py:43] Logged in user: S3ARKLR, role: superadmin
2023-10-30 17:32:50,267 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 17:32:50,267 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 17:33:32,624 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 17:33:32,624 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 17:34:17,517 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 17:34:17,517 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 17:34:17,517 INFO     [app.py:43] Logged in user: QRyriC, role: principal
2023-10-30 17:36:32,542 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-30 17:36:32,545 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-30 17:36:32,545 INFO     [app.py:43] Logged in user: 3b47R5, role: teacher
2023-10-31 09:47:04,711 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:47:04,717 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:47:04,718 INFO     [app.py:43] Logged in user: S3ARKLR, role: superadmin
2023-10-31 09:47:09,365 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:47:09,365 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:47:09,365 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:47:09,365 ERROR    [db_connector.py:23] Some error occurred
2023-10-31 09:49:11,087 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:49:11,089 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:49:11,089 INFO     [app.py:43] Logged in user: S3ARKLR, role: superadmin
2023-10-31 09:49:13,485 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:49:13,485 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:49:13,494 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:49:13,505 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:49:13,505 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:49:13,505 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:49:13,514 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:49:13,517 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:49:30,739 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:49:30,740 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:49:30,741 INFO     [app.py:43] Logged in user: QRyriC, role: principal
2023-10-31 09:49:33,815 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:49:33,815 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:52:08,799 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:52:08,800 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 09:52:08,800 INFO     [app.py:43] Logged in user: QRyriC, role: principal
2023-10-31 09:52:12,140 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 09:52:12,154 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 10:19:21,871 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 10:19:21,871 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 10:19:21,871 INFO     [app.py:43] Logged in user: S3ARKLR, role: superadmin
2023-10-31 10:20:20,159 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 10:20:20,160 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 10:20:20,161 INFO     [app.py:43] Logged in user: S3ARKLR, role: superadmin
2023-10-31 10:31:50,660 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 10:31:50,661 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 10:31:50,661 INFO     [app.py:41] Logged in user: S3ARKLR, role: superadmin
2023-10-31 14:41:24,238 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 14:41:24,238 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 14:42:45,535 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 14:42:45,536 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:06:26,127 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:06:26,127 ERROR    [db_connector.py:23] Some error occurred
2023-10-31 15:09:37,127 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:09:37,128 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:11:40,173 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:11:40,175 ERROR    [db_connector.py:23] Some error occurred
2023-10-31 15:13:27,996 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:13:27,996 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:13:40,403 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:13:40,404 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:14:32,433 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:14:32,434 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:15:52,115 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:15:52,116 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:16:57,787 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:16:57,788 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:18:03,992 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:18:03,994 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:18:19,474 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:18:19,474 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:19:28,642 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:19:28,642 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:21:59,081 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:21:59,082 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:21:59,084 INFO     [app.py:41] Logged in user: S3ARKLR, role: superadmin
2023-10-31 15:41:43,205 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:41:43,207 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 15:41:43,209 INFO     [app.py:41] Logged in user: S3ARKLR, role: superadmin
2023-10-31 15:41:49,740 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 15:41:49,745 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 16:06:37,828 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 16:06:37,831 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 16:06:37,832 INFO     [app.py:41] Logged in user: S3ARKLR, role: superadmin
2023-10-31 16:06:42,090 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 16:06:42,090 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 16:49:03,368 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 16:49:03,369 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 16:49:03,369 ERROR    [user_controller.py:29] Wrong Credentials
2023-10-31 16:49:21,319 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 16:49:21,320 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 16:49:21,320 ERROR    [user_controller.py:35] User 4JgkRa don't exists
2023-10-31 17:06:18,688 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:06:18,689 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:06:18,689 ERROR    [users.py:58] No such school present in the system
2023-10-31 17:06:18,689 INFO     [user_controller.py:66] User Saved to DB
2023-10-31 17:09:50,558 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:09:50,559 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:09:50,562 INFO     [app.py:41] Logged in user: S3ARKLR, role: superadmin
2023-10-31 17:09:54,105 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:09:54,120 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:09:54,120 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:09:54,120 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:09:54,138 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:09:54,138 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:09:54,140 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:09:54,149 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:11:26,327 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:11:26,336 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:11:50,910 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:11:50,919 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:13:38,935 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:13:38,935 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:13:38,935 INFO     [app.py:41] Logged in user: 3b47R5, role: teacher
2023-10-31 17:13:43,484 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:13:43,484 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:13:50,480 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:13:50,482 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:13:58,578 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:13:58,591 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 17:13:58,591 INFO     [issue_handler.py:34] Issue Created Successfully
2023-10-31 17:14:04,397 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 17:14:04,397 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 23:45:33,352 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 23:45:33,364 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 23:45:33,365 INFO     [app.py:41] Logged in user: QRyriC, role: principal
2023-10-31 23:45:58,625 DEBUG    [db_connector.py:18] Database connection initialise
2023-10-31 23:45:58,641 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-10-31 23:45:58,641 INFO     [event_handler.py:43] Added to Notice Board
2023-11-01 14:49:33,064 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:49:33,066 DEBUG    [initializer.py:28] Table Created only once
2023-11-01 14:49:33,066 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:49:51,890 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:49:51,891 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:49:51,891 INFO     [app.py:42] Logged in user: S4NUgHw, role: superadmin
2023-11-01 14:51:38,774 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:51:38,776 DEBUG    [initializer.py:28] Table Created only once
2023-11-01 14:51:38,776 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:51:51,803 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:51:51,803 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:51:51,803 INFO     [app.py:42] Logged in user: S4NUgHw, role: superadmin
2023-11-01 14:54:44,033 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:54:44,035 DEBUG    [initializer.py:28] Table Created only once
2023-11-01 14:54:44,035 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:54:53,273 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:54:53,275 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:54:53,275 INFO     [app.py:42] Logged in user: S4NUgHw, role: superadmin
2023-11-01 14:55:47,382 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:55:47,382 DEBUG    [initializer.py:28] Table Created only once
2023-11-01 14:55:47,385 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:55:57,046 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:55:57,047 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:55:57,047 INFO     [app.py:42] Logged in user: S4NUgHw, role: superadmin
2023-11-01 14:57:09,333 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:57:09,334 DEBUG    [initializer.py:28] Table Created only once
2023-11-01 14:57:09,334 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:57:20,562 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:57:20,562 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:57:20,562 INFO     [app.py:42] Logged in user: S4NUgHw, role: superadmin
2023-11-01 14:58:31,702 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:58:31,702 DEBUG    [initializer.py:28] Table Created only once
2023-11-01 14:58:31,702 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:58:42,263 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 14:58:42,265 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 14:58:42,265 INFO     [app.py:42] Logged in user: S4NUgHw, role: superadmin
2023-11-01 15:06:22,537 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:06:22,640 ERROR    [db_connector.py:23] Some error occurred
2023-11-01 15:07:06,736 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:07:06,737 DEBUG    [initializer.py:27] Table Created only once
2023-11-01 15:07:06,737 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:09:49,596 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:09:49,612 DEBUG    [initializer.py:27] Table Created only once
2023-11-01 15:09:49,612 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:10:05,602 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:10:05,602 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:10:05,602 ERROR    [user_controller.py:26] Wrong Credentials
2023-11-01 15:11:46,429 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:11:46,429 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:11:46,429 ERROR    [user_controller.py:26] Wrong Credentials
2023-11-01 15:21:12,170 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:21:12,172 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:21:12,172 ERROR    [users.py:59] No such school present in the system
2023-11-01 15:26:24,386 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:26:24,386 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:26:24,386 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:26:24,400 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:26:24,402 INFO     [users.py:136] User om priya principal Saved to Db
2023-11-01 15:26:24,402 INFO     [users.py:138] Principal Saved to DB
2023-11-01 15:26:39,993 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:26:39,995 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:26:39,995 ERROR    [user_controller.py:26] Wrong Credentials
2023-11-01 15:27:20,806 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:27:20,808 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:27:20,808 ERROR    [user_controller.py:29] Pending User DKgBeb tried to logged In
2023-11-01 15:28:05,148 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:28:05,149 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:28:05,149 INFO     [app.py:42] Logged in user: SWWcqZt, role: superadmin
2023-11-01 15:28:52,182 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:28:52,182 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:28:52,182 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:28:52,185 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:37:41,109 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:37:41,111 DEBUG    [initializer.py:27] Table Created only once
2023-11-01 15:37:41,111 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:37:51,257 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:37:51,259 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:37:51,259 INFO     [app.py:42] Logged in user: SWWcqZt, role: superadmin
2023-11-01 15:37:59,713 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:37:59,713 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:37:59,713 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:37:59,713 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:38:08,722 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:38:08,724 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:39:24,326 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:39:24,326 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:39:24,327 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:39:24,328 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:39:24,328 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:39:24,341 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:39:36,431 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:39:36,431 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:39:59,945 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:39:59,945 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:40:36,285 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:40:36,285 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:40:36,285 INFO     [app.py:42] Logged in user: DKgBeb, role: principal
2023-11-01 15:40:58,601 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:40:58,601 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:41:54,614 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:41:54,614 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:41:54,614 ERROR    [feedback_handler.py:24] No Feedbacks Found by user DKgBeb
2023-11-01 15:43:51,895 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:43:51,903 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 15:44:38,424 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 15:44:38,424 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 16:08:42,510 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 16:08:42,514 DEBUG    [initializer.py:27] Table Created only once
2023-11-01 16:08:42,514 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 16:10:01,194 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 16:10:01,194 DEBUG    [initializer.py:27] Table Created only once
2023-11-01 16:10:01,194 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 16:10:39,567 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 16:10:39,569 DEBUG    [db_connector.py:28] Saving and Closing the connection
2023-11-01 16:10:39,569 DEBUG    [db_connector.py:18] Database connection initialise
2023-11-01 16:10:39,581 ERROR    [db_connector.py:23] Some error occurred
2023-11-01 16:10:39,581 ERROR    [exception_handler.py:18] Something went wrong with db UNIQUE constraint failed: user.phone
Traceback (most recent call last):
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\utils\exception_handler.py", line 15, in exception_handler
    func(*args, **kwargs)
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\models\users.py", line 81, in save_teacher
    cursor.execute(insert_queries.INSERT_INTO_USER, user_tuple)
sqlite3.IntegrityError: UNIQUE constraint failed: user.phone
2023-11-02 09:25:31,203 DEBUG    [initializer.py:27] Table Created only once
2023-11-02 09:26:17,683 INFO     [users.py:84] User dummy1 teacher Saved to Db
2023-11-02 09:26:17,683 INFO     [users.py:86] Teacher Saved to DB
2023-11-02 09:27:13,659 INFO     [users.py:84] User dummy2 teacher Saved to Db
2023-11-02 09:27:13,659 INFO     [users.py:86] Teacher Saved to DB
2023-11-02 09:27:55,383 INFO     [users.py:84] User dummy3 teacher Saved to Db
2023-11-02 09:27:55,383 INFO     [users.py:86] Teacher Saved to DB
2023-11-02 09:28:07,238 INFO     [app.py:42] Logged in user: SWWcqZt, role: superadmin
2023-11-02 09:28:54,495 INFO     [users.py:139] User dummy4 principal Saved to Db
2023-11-02 09:28:54,496 INFO     [users.py:141] Principal Saved to DB
2023-11-02 09:29:41,145 INFO     [users.py:139] User dummy5 principal Saved to Db
2023-11-02 09:29:41,145 INFO     [users.py:141] Principal Saved to DB
2023-11-02 09:30:30,403 INFO     [users.py:139] User dummy6 principal Saved to Db
2023-11-02 09:30:30,403 INFO     [users.py:141] Principal Saved to DB
2023-11-02 09:30:39,875 INFO     [app.py:42] Logged in user: SWWcqZt, role: superadmin
2023-11-02 14:44:03,788 DEBUG    [initializer.py:27] Table Created only once
2023-11-02 15:23:57,455 DEBUG    [initializer.py:27] Table Created only once
2023-11-03 09:48:21,248 DEBUG    [initializer.py:27] Table Created only once
2023-11-03 09:50:18,038 DEBUG    [initializer.py:27] Table Created only once
2023-11-03 09:50:28,326 INFO     [app.py:44] Logged in user: SWWcqZt, role: superadmin
2023-11-03 12:29:56,331 DEBUG    [initializer.py:27] Table Created only once
2023-11-03 12:30:07,688 ERROR    [user_controller.py:27] Wrong Credentials
2023-11-03 12:31:37,538 DEBUG    [initializer.py:27] Table Created only once
2023-11-03 12:31:46,468 INFO     [app.py:44] Logged in user: SWWcqZt, role: superadmin
2023-11-03 12:31:57,758 WARNING  [principal_handler.py:60] Can't add more than one principal
2023-11-03 14:03:34,269 DEBUG    [initializer.py:27] Table Created only once
2023-11-03 14:03:43,543 INFO     [app.py:45] Logged in user: SWWcqZt, role: superadmin
2023-11-03 14:04:05,448 INFO     [app.py:45] Logged in user: 6mAmJF, role: principal
2023-11-03 14:15:07,149 DEBUG    [initializer.py:31] Table Created only once
2023-11-03 14:15:16,062 INFO     [app.py:45] Logged in user: SWWcqZt, role: superadmin
2023-11-06 13:58:42,957 DEBUG    [initializer.py:31] Table Created only once
2023-11-06 14:39:33,045 DEBUG    [initializer.py:31] Table Created only once
2023-11-06 14:39:49,225 DEBUG    [initializer.py:31] Table Created only once
2023-11-06 15:18:30,718 DEBUG    [initializer.py:31] Table Created only once
2023-11-06 17:58:21,693 DEBUG    [initializer.py:31] Table Created only once
2023-11-07 11:59:18,322 DEBUG    [initializer.py:31] Table Created only once
2023-11-07 12:00:18,288 DEBUG    [initializer.py:31] Table Created only once
2023-11-07 12:01:01,586 INFO     [user_controller.py:86] Initiating saving teacher
2023-11-07 12:01:01,599 INFO     [teachers.py:68] User dummy teacher Saved to Db
2023-11-07 12:01:01,602 INFO     [teachers.py:70] Teacher Saved to DB
2023-11-07 15:33:10,509 DEBUG    [initializer.py:31] Table Created only once
2023-11-07 15:33:24,226 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-07 15:33:30,482 ERROR    [principal_handler.py:75] No Principal Found
2023-11-07 16:45:30,948 DEBUG    [initializer.py:31] Table Created only once
2023-11-07 16:45:41,129 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-08 09:08:37,429 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 09:49:18,026 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 09:49:33,396 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-16 09:50:59,522 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 09:51:09,309 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-16 09:52:24,555 INFO     [user_controller.py:89] Initiating saving principal
2023-11-16 09:52:24,566 ERROR    [db_connector.py:22] Some error occurred
2023-11-16 09:52:24,567 ERROR    [exception_handler.py:22] Tried to insert duplicate values UNIQUE constraint failed: user.phone
Traceback (most recent call last):
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\src\utils\exception_handler.py", line 16, in exception_handler
    func(*args, **kwargs)
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\src\models\principals.py", line 66, in save_principal
    cursor.execute(CreateTable.INSERT_INTO_USER, user_tuple)
sqlite3.IntegrityError: UNIQUE constraint failed: user.phone
2023-11-16 09:53:19,193 INFO     [user_controller.py:89] Initiating saving principal
2023-11-16 09:53:19,217 INFO     [principals.py:69] User dummy kumar principal Saved to Db
2023-11-16 09:53:19,217 INFO     [principals.py:71] Principal Saved to DB
2023-11-16 09:57:03,711 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 09:57:22,738 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-16 09:57:27,476 ERROR    [principal_handler.py:72] No Principal Found
2023-11-16 09:57:57,941 INFO     [principal_handler.py:51] Invalid Id's Given
2023-11-16 09:58:47,461 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 09:59:21,894 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-16 09:59:51,204 ERROR    [user_controller.py:31] Wrong Credentials
2023-11-16 10:00:19,847 ERROR    [user_controller.py:31] Wrong Credentials
2023-11-16 10:00:49,427 INFO     [app.py:45] Logged in user: 4G4KmC, role: principal
2023-11-16 10:01:04,743 ERROR    [issue_handler.py:21] No issues Found
2023-11-16 10:09:13,152 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 10:09:35,405 INFO     [app.py:45] Logged in user: 4G4KmC, role: principal
2023-11-16 10:10:12,731 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 10:10:20,343 INFO     [app.py:45] Logged in user: 4G4KmC, role: principal
2023-11-16 10:10:53,623 ERROR    [db_connector.py:22] Some error occurred
2023-11-16 10:10:53,624 ERROR    [exception_handler.py:19] Something went wrong while executing Query near ",": syntax error
Traceback (most recent call last):
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\src\utils\exception_handler.py", line 16, in exception_handler
    func(*args, **kwargs)
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\src\controllers\handlers\teacher_handler.py", line 53, in approve_teacher
    DAO.execute_non_returning_query(TeacherQueries.APPROVE_TEACHER, (teacher_id,))
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\src\database\database_access.py", line 18, in execute_non_returning_query
    cursor.execute(query, params)
sqlite3.OperationalError: near ",": syntax error
2023-11-16 10:50:05,966 DEBUG    [initializer.py:31] Table Created only once
2023-11-16 10:50:18,767 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-17 01:29:43,260 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 01:30:45,503 INFO     [user_controller.py:89] Initiating saving principal
2023-11-17 01:30:45,517 INFO     [principals.py:69] User dummy yadav principal Saved to Db
2023-11-17 01:30:45,517 INFO     [principals.py:71] Principal Saved to DB
2023-11-17 01:32:28,014 INFO     [user_controller.py:89] Initiating saving principal
2023-11-17 01:32:28,037 INFO     [principals.py:69] User dummy uzumaki principal Saved to Db
2023-11-17 01:32:28,038 INFO     [principals.py:71] Principal Saved to DB
2023-11-17 01:32:39,953 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-17 01:33:47,293 WARNING  [principal_handler.py:62] Can't add more than one principal
2023-11-17 01:34:26,247 WARNING  [principal_handler.py:62] Can't add more than one principal
2023-11-17 01:37:20,646 ERROR    [principal_handler.py:194] No Such Principal With id 3QP99X
2023-11-17 01:37:50,903 INFO     [principal_handler.py:53] Invalid Id's Given
2023-11-17 01:38:05,623 INFO     [principal_handler.py:53] Invalid Id's Given
2023-11-17 01:42:38,718 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 01:42:59,053 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-17 01:43:14,999 INFO     [principal_handler.py:53] Invalid Id's Given
2023-11-17 01:43:29,414 INFO     [principal_handler.py:53] Invalid Id's Given
2023-11-17 01:45:15,817 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 01:45:27,079 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-17 01:45:34,572 INFO     [principal_handler.py:54] Invalid Id's Given
2023-11-17 01:47:13,184 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 01:47:23,303 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-17 01:47:28,422 INFO     [principal_handler.py:56] Invalid Id's Given
2023-11-17 01:48:34,348 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 01:48:46,301 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-17 01:54:45,451 INFO     [super_admin_controller.py:127] No Pending Leave Request
2023-11-17 01:58:29,798 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 01:59:42,937 INFO     [user_controller.py:85] Initiating saving teacher
2023-11-17 01:59:42,958 INFO     [teachers.py:67] User dummy hinata teacher Saved to Db
2023-11-17 01:59:42,959 INFO     [teachers.py:69] Teacher Saved to DB
2023-11-17 02:01:59,840 INFO     [user_controller.py:85] Initiating saving teacher
2023-11-17 02:01:59,851 INFO     [teachers.py:67] User dummy neji teacher Saved to Db
2023-11-17 02:01:59,851 INFO     [teachers.py:69] Teacher Saved to DB
2023-11-17 02:02:12,907 ERROR    [user_controller.py:31] Wrong Credentials
2023-11-17 02:02:50,812 INFO     [app.py:45] Logged in user: 3QP99X, role: principal
2023-11-17 02:02:59,433 ERROR    [issue_handler.py:21] No issues Found
2023-11-17 02:03:25,281 ERROR    [leave_handler.py:51] No Leaves Record Found for user 3QP99X
2023-11-17 02:03:41,833 ERROR    [leave_handler.py:27] 16-11-2023 leave_date is previous to curr date 17-11-2023
2023-11-17 02:03:57,347 INFO     [leave_handler.py:41] Applied to leave by user 3QP99X
2023-11-17 02:05:07,489 ERROR    [event_handler.py:24] No Records On Notice Board
2023-11-17 02:05:18,898 INFO     [event_handler.py:47] Added to Notice Board
2023-11-17 02:05:39,209 ERROR    [feedback_handler.py:28] No Feedbacks Found by user 3QP99X
2023-11-17 02:05:43,033 ERROR    [feedback_handler.py:46] No Teacher Present in the system
2023-11-17 02:06:22,990 ERROR    [teacher_handler.py:65] No Teacher Found
2023-11-17 02:09:55,256 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 02:10:21,793 INFO     [app.py:45] Logged in user: 3QP99X, role: principal
2023-11-17 02:11:32,174 ERROR    [feedback_handler.py:63] Wrong Teacher Id
2023-11-17 02:11:55,368 INFO     [feedback_handler.py:78] Feedback Created
2023-11-17 02:12:50,930 ERROR    [user_controller.py:37] User 462scd don't exists
2023-11-17 02:13:32,638 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 02:13:57,465 ERROR    [user_controller.py:31] Wrong Credentials
2023-11-17 02:14:22,145 INFO     [app.py:45] Logged in user: 4X44EK, role: teacher
2023-11-17 02:14:46,575 INFO     [issue_handler.py:44] Issue Created Successfully
2023-11-17 02:14:53,004 ERROR    [helper_function.py:19] No Salary History Found
2023-11-17 02:15:34,917 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 02:16:01,250 INFO     [app.py:45] Logged in user: S4WnX5h, role: superadmin
2023-11-17 02:16:50,055 INFO     [super_admin_controller.py:128] No Pending Leave Request
2023-11-17 03:29:50,227 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 03:30:14,506 INFO     [app.py:43] Logged in user: S4WnX5h, role: superadmin
2023-11-17 03:37:05,413 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 03:37:14,882 INFO     [app.py:43] Logged in user: 3QP99X, role: principal
2023-11-17 03:37:52,426 INFO     [app.py:43] Logged in user: 3QP99X, role: principal
2023-11-17 09:47:55,695 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 09:48:14,831 INFO     [app.py:43] Logged in user: SqHhwbc, role: superadmin
2023-11-17 11:18:35,706 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 11:19:14,393 INFO     [user_controller.py:89] Initiating saving principal
2023-11-17 11:19:14,427 INFO     [principals.py:69] User dummy kumar principal Saved to Db
2023-11-17 11:19:14,427 INFO     [principals.py:71] Principal Saved to DB
2023-11-17 11:20:15,133 INFO     [user_controller.py:85] Initiating saving teacher
2023-11-17 11:20:15,155 INFO     [teachers.py:66] User dummy uzumaki teacher Saved to Db
2023-11-17 11:20:15,155 INFO     [teachers.py:68] Teacher Saved to DB
2023-11-17 11:20:33,498 INFO     [app.py:43] Logged in user: SqHhwbc, role: superadmin
2023-11-17 11:21:33,886 INFO     [app.py:43] Logged in user: 3Uk9WA, role: principal
2023-11-17 11:22:08,036 INFO     [app.py:43] Logged in user: 4Dkrei, role: teacher
2023-11-17 11:22:11,417 ERROR    [helper_function.py:81] 
No such Feedback Found

2023-11-17 13:22:32,209 DEBUG    [initializer.py:31] Table Created only once
2023-11-17 13:23:36,140 INFO     [app.py:43] Logged in user: SqHhwbc, role: superadmin
2023-11-17 13:24:49,794 ERROR    [helper_function.py:81] 
No such Principal Found

2023-11-17 13:28:39,441 INFO     [user_controller.py:85] Initiating saving teacher
2023-11-17 13:28:39,453 ERROR    [db_connector.py:21] Some error occurred
2023-11-17 13:28:39,455 ERROR    [exception_handler.py:22] Tried to insert duplicate values UNIQUE constraint failed: credential.username
Traceback (most recent call last):
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\src\utils\exception_handler.py", line 16, in exception_handler
    func(*args, **kwargs)
  File "C:\Users\opriya\OneDrive - WatchGuard Technologies Inc\python minor project\school management system\src\models\teachers.py", line 61, in save_teacher
    cursor.execute(CreateTable.INSERT_INTO_CREDENTIAL, cred_tuple)
sqlite3.IntegrityError: UNIQUE constraint failed: credential.username
2023-11-17 13:30:14,548 ERROR    [user_controller.py:31] Wrong Credentials
2023-11-17 13:30:30,808 INFO     [app.py:43] Logged in user: 4Dkrei, role: teacher
2023-11-17 13:30:51,382 INFO     [issue_handler.py:43] Issue Created Successfully
2023-11-17 13:31:46,401 ERROR    [helper_function.py:81] 
No such Feedback Found

2023-11-17 13:32:08,365 INFO     [app.py:43] Logged in user: 3Uk9WA, role: principal
2023-11-17 13:32:20,729 ERROR    [helper_function.py:81] 
No such FeedBack Found

2023-11-17 13:33:23,822 INFO     [feedback_handler.py:75] Feedback Created
2023-11-17 13:33:41,475 INFO     [app.py:43] Logged in user: 4Dkrei, role: teacher
2023-11-17 13:33:56,430 ERROR    [helper_function.py:22] No Salary History Found
